[template]
exclude = [
    "README.md",
    "favicon.ico",
    "template.json",
    "**/README.md",
    "**/favicon.ico",
    "**/target",
    "**/.git",
    "**/Cargo.lock"]

# template locally doesn't exclude files when test in windows, not sure about linux